### ISSUE TITLE
Docs Site

### ISSUE THREAD

**Issue by rickwysocki** [eco-infra/ecoinfra#29]
It would be useful to run a documentation site out of the /docs folder. This should be easy to do using GitHub pages. There are a few different tools that would make sense:

- [Jekyll](https://jekyllrb.com/), using something like the [Just the Docs theme](https://just-the-docs.com/): Easy to set up and get running.
- [Read the Docs](https://about.readthedocs.com/features/): Likely a bit more complicated to get configured, but also more feature-rich.

If this seems like an interesting idea, it would be useful to both pick a tool and also put together a list of content pages that would be needed in the documentation.

**Comment by iamdavidmt** [comment]
Love it - I think I'm in favour of jekyll considering its effort to setup seems [small](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll) - I can have a look at getting something setup this weekend.

**Comment by rickwysocki** [comment]
Cool! Yes, Jekyll is very easy to get going. If you'd like, I'm happy to push my test Jekyll setup in the repository in a separate branch/pull request for you to take a look at, but I totally understand if you'd like to handle it on your end. Either way, I do believe you'll need to configure the GitHub pages side of things on your end.

**Comment by iamdavidmt** [comment]
Thanks for all the work @rickwysocki - long overdue fix but I've resolved the gem issue by using a remote_theme isntead;

**Comment by rickwysocki** [comment]
Sorry for just swinging back to this, but cool! Let me know if there's anything I can be helpful with.
